REGISTRY=quay.io/cvicensa

OCP_PASSWORD=openshift

OC_VERSION=4.5

WORKSHOP_NAME=lab-ossm
WORKSHOP_VERSION=4.5

WORKSHOP_NAME=lab-ossm
#WORKSHOP_IMAGE=quay.io/thoraxe/lab-ossm:production

RESOURCE_BUDGET=medium
MAX_SESSION_AGE=3600
IDLE_TIMEOUT=300
SPAWNER_MODE=hosted-workshop
